# Generated by Django 5.1.7 on 2025-03-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.CharField(default='Laptops', max_length=255),
            preserve_default=False,
        ),
    ]
